version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '6000:27017'
    env_file:
      - ./backend/.env
    volumes:
      - mongo-db:/data/db
    restart: unless-stopped

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
    restart: unless-stopped
volumes:
  mongo-db:
  redis:
